---
title: "HelpDocument_week 4"
author: "preethi"
date: "1/13/2020"
output: pdf_document
---

## Help Document for Week 4's assignment

The programming assignment at hand:

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. 
Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

## Your Shiny Application

Write a shiny application with associated supporting documentation. 
This includes:
The app on the shiny servers
The supporting documentation along with the code (server and UI code) on github

The app should have:

Some form of input (widget: textbox, radio button, checkbox, ...)
Some operation on the ui input in sever.R
Some reactive output displayed as a result of server calculations

## Your Reproducible Pitch Presentation

OK, you've made your shiny app, now it's time to make your pitch. You get 5 slides (inclusive of the title slide) to pitch a your app. You're going to create a web page using Slidify or Rstudio Presenter with an html5 slide deck.

Here's what you need

5 slides to pitch our idea done in Slidify or Rstudio Presenter
Your presentation pushed to github or Rpubs
A link to your github or Rpubs presentation pasted into the provided text box
Your presentation must satisfy the following

It must be done in Slidify or Rstudio Presenter
It must be 5 pages
It must be hosted on github or Rpubs
It must contained some embedded R code that gets run when slidifying the document

## Documentation for running the shiny app

The data for the shiny app was gotten from <https://openbudgetsindia.org/dataset/sector-specific-indicators-of-state-expenditure>

- Download the file titled "sector-specific-state-aggregate-expenditure-2013-14-actuals-to-2016-17-budget-estimates.csv"

- Clean the data (run global.r)

- And run the filesnames (server.r) and (ui.r) 

- All of which are in the github repository that is attached here

The purpose of this application is to help observe time-trends in the sectorwise budget data for the different states in India. 




